using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
namespace HTMLUICompiler.CssRules
{
    public class CssHelpers
    {
        public enum CssLexicalTokens
        {
            COLOR,
            OPACITY,
            BACKGROUND,
            BACKGROUNDATTACHMENT,
            BACKGROUNDCOLOR,
            BACKGROUNDIMAGE,
            BACKGROUNDPOSITION,
            BACKGROUNDREPEAT,
            BACKGROUNDCLIP,
            BACKGROUNDORIGIN,
            BACKGROUNDSIZE,
            BORDER,
            BORDERBOTTOM,
            BORDERBOTTOMCOLOR,
            BORDERBOTTOMLEFTRADIUS,
            BORDERBOTTOMRIGHTRADIUS,
            BORDERBOTTOMSTYLE,
            BORDERBOTTOMWIDTH,
            BORDERCOLOR,
            BORDERIMAGE,
            BORDERIMAGEOUTSET,
            BORDERIMAGEREPEAT,
            BORDERIMAGESLICE,
            BORDERIMAGESOURCE,
            BORDERIMAGEWIDTH,
            BORDERLEFT,
            BORDERLEFTCOLOR,
            BORDERLEFTSTYLE,
            BORDERLEFTWIDTH,
            BORDERRADIUS,
            BORDERRIGHT,
            BORDERRIGHTCOLOR,
            BORDERRIGHTSTYLE,
            BORDERRIGHTWIDTH,
            BORDERSTYLE,
            BORDERTOP,
            BORDERTOPCOLOR,
            BORDERTOPLEFTRADIUS,
            BORDERTOPRIGHTRADIUS,
            BORDERTOPSTYLE,
            BORDERTOPWIDTH,
            BORDERWIDTH,
            BOXDECORATIONBREAK,
            BOXSHADOW,
            BOTTOM,
            CLEAR,
            CLIP,
            FLOATING,
            HEIGHT,
            LEFT,
            OVERFLOW,
            OVERFLOWX,
            OVERFLOWY,
            PADDING,
            PADDINGBOTTOM,
            PADDINGLEFT,
            PADDINGRIGHT,
            PADDINGTOP,
            POSITION,
            RIGHT,
            TOP,
            VISIBILITY,
            WIDTH,
            VERTICALALIGN,
            ZINDEX,
            ALIGNCONTENT,
            ALIGNITEMS,
            ALIGNSELF,
            DISPLAY,
            FLEX,
            FLEXBASIS,
            FLEXDIRECTION,
            FLEXFLOW,
            FLEXGROW,
            FLEXSHRINK,
            FLEXWRAP,
            JUSTIFYCONTENT,
            MARGIN,
            MARGINBOTTOM,
            MARGINLEFT,
            MARGINRIGHT,
            MARGINTOP,
            MAXHEIGHT,
            MAXWIDTH,
            MINHEIGHT,
            MINWIDTH,
            ORDER,
            HANGINGPUNCTUATION,
            HYPHENS,
            LETTERSPACING,
            LINEBREAK,
            LINEHEIGHT,
            OVERFLOWWRAP,
            TABSIZE,
            TEXTALIGN,
            TEXTALIGNLAST,
            TEXTINDENT,
            TEXTJUSTIFY,
            TEXTTRANSFORM,
            WHITESPACE,
            WORDBREAK,
            WORDSPACING,
            WORDWRAP,
            TEXTDECORATION,
            TEXTDECORATIONCOLOR,
            TEXTDECORATIONLINE,
            TEXTDECORATIONSTYLE,
            TEXTSHADOW,
            TEXTUNDERLINEPOSITION,
            FONT,
            FONTFAMILY,
            FONTFEATURESETTING,
            FONTFEATUREVALUES,
            FONTKERNING,
            FONTLANGUAGEOVERRIDE,
            FONTSYNTHESIS,
            FONTVARIANTALTERNATES,
            FONTVARIANTCAPS,
            FONTVARIANTEASTASIAN,
            FONTVARIANTLIGATURES,
            FONTVARIANTNUMERIC,
            FONTVARIANTPOSITION,
            FONTSIZE,
            FONTSTYLE,
            FONTVARIANT,
            FONTWEIGHT,
            FONTFACE,
            FONTSIZEADJUST,
            FONTSTRETCH,
            DIRECTION,
            TEXTORIENTATION,
            TEXTCOMBINEHORIZONTAL,
            UNICODEBIDI,
            WRITINGMODE,
            BORDERCOLLAPSE,
            BORDERSPACING,
            CAPTIONSIDE,
            EMPTYCELLS,
            TABLELAYOUT,
            COUNTERINCREMENT,
            COUNTERRESET,
            LISTSTYLE,
            LISTSTYLEIMAGE,
            LISTSTYLEPOSITION,
            LISTSTYLETYPE,
            KEYFRAMES,
            ANIMATION,
            ANIMATIONDELAY,
            ANIMATIONDIRECTION,
            ANIMATIONDURATION,
            ANIMATIONFILLMODE,
            ANIMATIONITERATIONCOUNT,
            ANIMATIONNAME,
            ANIMATIONTIMINGFUNCTION,
            ANIMATIONPLAYSTATE,
            BACKFACEVISIBILITY,
            PERSPECTIVE,
            PERSPECTIVEORIGIN,
            TRANSFORM,
            TRANSFORMORIGIN,
            TRANSFORMSTYLE,
            TRANSITIONPROPERTY,
            TRANSITION,
            TRANSITIONDURATION,
            TRANSITIONTIMINGFUNCTION,
            TRANSITIONDELAY,
            BOXSIZING,
            CONTENT,
            CURSOR,
            ICON,
            IMEMODE,
            NAVDOWN,
            NAVINDEX,
            NAVLEFT,
            NAVRIGHT,
            NAVUP,
            OUTLINE,
            OUTLINECOLOR,
            OUTLINEOFFSET,
            OUTLINESTYLE,
            OUTLINEWIDTH,
            RESIZE,
            TEXTOVERFLOW,
            BREAKAFTER,
            BREAKBEFORE,
            BREAKINSIDE,
            COLUMNCOUNT,
            COLUMNFILL,
            COLUMNGAP,
            COLUMNRULE,
            COLUMNRULECOLOR,
            COLUMNRULESTYLE,
            COLUMNRULEWIDTH,
            COLUMNSPAN,
            COLUMNWIDTH,
            COLUMNS,
            WIDOWS,
            ORPHANS,
            PAGEBREAKAFTER,
            PAGEBREAKBEFORE,
            PAGEBREAKINSIDE,
            MARKS,
            QUOTES,
            FILTER,
            IMAGEORIENTATION,
            IMAGERENDERING,
            IMAGERESOLUTION,
            OBJECTFIT,
            OBJECTPOSITION,
            MASK,
            MASKTYPE,
            MARK,
            MARKAFTER,
            MARKBEFORE,
            PHONEMES,
            REST,
            RESTAFTER,
            RESTBEFORE,
            VOICEBALANCE,
            VOICEDURATION,
            VOICEPITCH,
            VOICEPITCHRANGE,
            VOICERATE,
            VOICESTRESS,
            VOICEVOLUME,
            MARQUEEDIRECTION,
            MARQUEEPLAYCOUNT,
            MARQUEESPEED,
            MARQUEESTYLE
        };

        public static Dictionary<string, CssLexicalTokens> StringToCssToken = new Dictionary<string, CssLexicalTokens>()
        {
            {"color", CssLexicalTokens.COLOR},
            {"opacity", CssLexicalTokens.OPACITY},
            {"background", CssLexicalTokens.BACKGROUND},
            {"background-attachment", CssLexicalTokens.BACKGROUNDATTACHMENT},
            {"background-color", CssLexicalTokens.BACKGROUNDCOLOR},
            {"background-image", CssLexicalTokens.BACKGROUNDIMAGE},
            {"background-position", CssLexicalTokens.BACKGROUNDPOSITION},
            {"background-repeat", CssLexicalTokens.BACKGROUNDREPEAT},
            {"background-clip", CssLexicalTokens.BACKGROUNDCLIP},
            {"background-origin", CssLexicalTokens.BACKGROUNDORIGIN},
            {"background-size", CssLexicalTokens.BACKGROUNDSIZE},
            {"border", CssLexicalTokens.BORDER},
            {"border-bottom", CssLexicalTokens.BORDERBOTTOM},
            {"border-bottom-color", CssLexicalTokens.BORDERBOTTOMCOLOR},
            {"border-bottom-left-radius", CssLexicalTokens.BORDERBOTTOMLEFTRADIUS},
            {"border-bottom-right-radius", CssLexicalTokens.BORDERBOTTOMRIGHTRADIUS},
            {"border-bottom-style", CssLexicalTokens.BORDERBOTTOMSTYLE},
            {"border-bottom-width", CssLexicalTokens.BORDERBOTTOMWIDTH},
            {"border-color", CssLexicalTokens.BORDERCOLOR},
            {"border-image", CssLexicalTokens.BORDERIMAGE},
            {"border-image-outset", CssLexicalTokens.BORDERIMAGEOUTSET},
            {"border-image-repeat", CssLexicalTokens.BORDERIMAGEREPEAT},
            {"border-image-slice", CssLexicalTokens.BORDERIMAGESLICE},
            {"border-image-source", CssLexicalTokens.BORDERIMAGESOURCE},
            {"border-image-width", CssLexicalTokens.BORDERIMAGEWIDTH},
            {"border-left", CssLexicalTokens.BORDERLEFT},
            {"border-left-color", CssLexicalTokens.BORDERLEFTCOLOR},
            {"border-left-style", CssLexicalTokens.BORDERLEFTSTYLE},
            {"border-left-width", CssLexicalTokens.BORDERLEFTWIDTH},
            {"border-radius", CssLexicalTokens.BORDERRADIUS},
            {"border-right", CssLexicalTokens.BORDERRIGHT},
            {"border-right-color", CssLexicalTokens.BORDERRIGHTCOLOR},
            {"border-right-style", CssLexicalTokens.BORDERRIGHTSTYLE},
            {"border-right-width", CssLexicalTokens.BORDERRIGHTWIDTH},
            {"border-style", CssLexicalTokens.BORDERSTYLE},
            {"border-top", CssLexicalTokens.BORDERTOP},
            {"border-top-color", CssLexicalTokens.BORDERTOPCOLOR},
            {"border-top-left-radius", CssLexicalTokens.BORDERTOPLEFTRADIUS},
            {"border-top-right-radius", CssLexicalTokens.BORDERTOPRIGHTRADIUS},
            {"border-top-style", CssLexicalTokens.BORDERTOPSTYLE},
            {"border-top-width", CssLexicalTokens.BORDERTOPWIDTH},
            {"border-width", CssLexicalTokens.BORDERWIDTH},
            {"box-decoration-break", CssLexicalTokens.BOXDECORATIONBREAK},
            {"box-shadow", CssLexicalTokens.BOXSHADOW},
            {"bottom", CssLexicalTokens.BOTTOM},
            {"clear", CssLexicalTokens.CLEAR},
            {"clip", CssLexicalTokens.CLIP},
            {"display", CssLexicalTokens.DISPLAY},
            {"float", CssLexicalTokens.FLOATING},
            {"height", CssLexicalTokens.HEIGHT},
            {"left", CssLexicalTokens.LEFT},
            {"overflow", CssLexicalTokens.OVERFLOW},
            {"overflow-x", CssLexicalTokens.OVERFLOWX},
            {"overflow-y", CssLexicalTokens.OVERFLOWY},
            {"padding", CssLexicalTokens.PADDING},
            {"padding-bottom", CssLexicalTokens.PADDINGBOTTOM},
            {"padding-left", CssLexicalTokens.PADDINGLEFT},
            {"padding-right", CssLexicalTokens.PADDINGRIGHT},
            {"padding-top", CssLexicalTokens.PADDINGTOP},
            {"position", CssLexicalTokens.POSITION},
            {"right", CssLexicalTokens.RIGHT},
            {"top", CssLexicalTokens.TOP},
            {"visibility", CssLexicalTokens.VISIBILITY},
            {"width", CssLexicalTokens.WIDTH},
            {"vertical-align", CssLexicalTokens.VERTICALALIGN},
            {"z-index", CssLexicalTokens.ZINDEX},
            {"align-content", CssLexicalTokens.ALIGNCONTENT},
            {"align-items", CssLexicalTokens.ALIGNITEMS},
            {"align-self", CssLexicalTokens.ALIGNSELF},
            {"flex", CssLexicalTokens.FLEX},
            {"flex-basis", CssLexicalTokens.FLEXBASIS},
            {"flex-direction", CssLexicalTokens.FLEXDIRECTION},
            {"flex-flow", CssLexicalTokens.FLEXFLOW},
            {"flex-grow", CssLexicalTokens.FLEXGROW},
            {"flex-shrink", CssLexicalTokens.FLEXSHRINK},
            {"flex-wrap", CssLexicalTokens.FLEXWRAP},
            {"justify-content", CssLexicalTokens.JUSTIFYCONTENT},
            {"margin", CssLexicalTokens.MARGIN},
            {"margin-bottom", CssLexicalTokens.MARGINBOTTOM},
            {"margin-left", CssLexicalTokens.MARGINLEFT},
            {"margin-right", CssLexicalTokens.MARGINRIGHT},
            {"margin-top", CssLexicalTokens.MARGINTOP},
            {"max-height", CssLexicalTokens.MAXHEIGHT},
            {"max-width", CssLexicalTokens.MAXWIDTH},
            {"min-height", CssLexicalTokens.MINHEIGHT},
            {"min-width", CssLexicalTokens.MINWIDTH},
            {"order", CssLexicalTokens.ORDER},
            {"hanging-punctuation", CssLexicalTokens.HANGINGPUNCTUATION},
            {"hyphens", CssLexicalTokens.HYPHENS},
            {"letter-spacing", CssLexicalTokens.LETTERSPACING},
            {"line-break", CssLexicalTokens.LINEBREAK},
            {"line-height", CssLexicalTokens.LINEHEIGHT},
            {"overflow-wrap", CssLexicalTokens.OVERFLOWWRAP},
            {"tab-size", CssLexicalTokens.TABSIZE},
            {"text-align", CssLexicalTokens.TEXTALIGN},
            {"text-align-last", CssLexicalTokens.TEXTALIGNLAST},
            {"text-indent", CssLexicalTokens.TEXTINDENT},
            {"text-justify", CssLexicalTokens.TEXTJUSTIFY},
            {"text-transform", CssLexicalTokens.TEXTTRANSFORM},
            {"white-space", CssLexicalTokens.WHITESPACE},
            {"word-break", CssLexicalTokens.WORDBREAK},
            {"word-spacing", CssLexicalTokens.WORDSPACING},
            {"word-wrap", CssLexicalTokens.WORDWRAP},
            {"text-decoration", CssLexicalTokens.TEXTDECORATION},
            {"text-decoration-color", CssLexicalTokens.TEXTDECORATIONCOLOR},
            {"text-decoration-line", CssLexicalTokens.TEXTDECORATIONLINE},
            {"text-decoration-style", CssLexicalTokens.TEXTDECORATIONSTYLE},
            {"text-shadow", CssLexicalTokens.TEXTSHADOW},
            {"text-underline-position", CssLexicalTokens.TEXTUNDERLINEPOSITION},
            {"font", CssLexicalTokens.FONT},
            {"font-family", CssLexicalTokens.FONTFAMILY},
            {"font-feature-setting", CssLexicalTokens.FONTFEATURESETTING},
            {"@font-feature-values", CssLexicalTokens.FONTFEATUREVALUES},
            {"font-kerning", CssLexicalTokens.FONTKERNING},
            {"font-language-override", CssLexicalTokens.FONTLANGUAGEOVERRIDE},
            {"font-synthesis", CssLexicalTokens.FONTSYNTHESIS},
            {"font-variant-alternates", CssLexicalTokens.FONTVARIANTALTERNATES},
            {"font-variant-caps", CssLexicalTokens.FONTVARIANTCAPS},
            {"font-variant-east-asian", CssLexicalTokens.FONTVARIANTEASTASIAN},
            {"font-variant-ligatures", CssLexicalTokens.FONTVARIANTLIGATURES},
            {"font-variant-numeric", CssLexicalTokens.FONTVARIANTNUMERIC},
            {"font-variant-position", CssLexicalTokens.FONTVARIANTPOSITION},
            {"font-size", CssLexicalTokens.FONTSIZE},
            {"font-style", CssLexicalTokens.FONTSTYLE},
            {"font-variant", CssLexicalTokens.FONTVARIANT},
            {"font-weight", CssLexicalTokens.FONTWEIGHT},
            {"@font-face", CssLexicalTokens.FONTFACE},
            {"font-size-adjust", CssLexicalTokens.FONTSIZEADJUST},
            {"font-stretch", CssLexicalTokens.FONTSTRETCH},
            {"direction", CssLexicalTokens.DIRECTION},
            {"text-orientation", CssLexicalTokens.TEXTORIENTATION},
            {"text-combine-horizontal", CssLexicalTokens.TEXTCOMBINEHORIZONTAL},
            {"unicode-bidi", CssLexicalTokens.UNICODEBIDI},
            {"writing-mode", CssLexicalTokens.WRITINGMODE},
            {"border-collapse", CssLexicalTokens.BORDERCOLLAPSE},
            {"border-spacing", CssLexicalTokens.BORDERSPACING},
            {"caption-side", CssLexicalTokens.CAPTIONSIDE},
            {"empty-cells", CssLexicalTokens.EMPTYCELLS},
            {"table-layout", CssLexicalTokens.TABLELAYOUT},
            {"counter-increment", CssLexicalTokens.COUNTERINCREMENT},
            {"counter-reset", CssLexicalTokens.COUNTERRESET},
            {"list-style", CssLexicalTokens.LISTSTYLE},
            {"list-style-image", CssLexicalTokens.LISTSTYLEIMAGE},
            {"list-style-position", CssLexicalTokens.LISTSTYLEPOSITION},
            {"list-style-type", CssLexicalTokens.LISTSTYLETYPE},
            {"@keyframes", CssLexicalTokens.KEYFRAMES},
            {"animation", CssLexicalTokens.ANIMATION},
            {"animation-delay", CssLexicalTokens.ANIMATIONDELAY},
            {"animation-direction", CssLexicalTokens.ANIMATIONDIRECTION},
            {"animation-duration", CssLexicalTokens.ANIMATIONDURATION},
            {"animation-fill-mode", CssLexicalTokens.ANIMATIONFILLMODE},
            {"animation-iteration-count", CssLexicalTokens.ANIMATIONITERATIONCOUNT},
            {"animation-name", CssLexicalTokens.ANIMATIONNAME},
            {"animation-timing-function", CssLexicalTokens.ANIMATIONTIMINGFUNCTION},
            {"animation-play-state", CssLexicalTokens.ANIMATIONPLAYSTATE},
            {"backface-visibility", CssLexicalTokens.BACKFACEVISIBILITY},
            {"perspective", CssLexicalTokens.PERSPECTIVE},
            {"perspective-origin", CssLexicalTokens.PERSPECTIVEORIGIN},
            {"transform", CssLexicalTokens.TRANSFORM},
            {"transform-origin", CssLexicalTokens.TRANSFORMORIGIN},
            {"transform-style", CssLexicalTokens.TRANSFORMSTYLE},
            {"transition", CssLexicalTokens.TRANSITION},
            {"transition-property", CssLexicalTokens.TRANSITIONPROPERTY},
            {"transition-duration", CssLexicalTokens.TRANSITIONDURATION},
            {"transition-timing-function", CssLexicalTokens.TRANSITIONTIMINGFUNCTION},
            {"transition-delay", CssLexicalTokens.TRANSITIONDELAY},
            {"box-sizing", CssLexicalTokens.BOXSIZING},
            {"content", CssLexicalTokens.CONTENT},
            {"cursor", CssLexicalTokens.CURSOR},
            {"icon", CssLexicalTokens.ICON},
            {"ime-mode", CssLexicalTokens.IMEMODE},
            {"nav-down", CssLexicalTokens.NAVDOWN},
            {"nav-index", CssLexicalTokens.NAVINDEX},
            {"nav-left", CssLexicalTokens.NAVLEFT},
            {"nav-right", CssLexicalTokens.NAVRIGHT},
            {"nav-up", CssLexicalTokens.NAVUP},
            {"outline", CssLexicalTokens.OUTLINE},
            {"outline-color", CssLexicalTokens.OUTLINECOLOR},
            {"outline-offset", CssLexicalTokens.OUTLINEOFFSET},
            {"outline-style", CssLexicalTokens.OUTLINESTYLE},
            {"outline-width", CssLexicalTokens.OUTLINEWIDTH},
            {"resize", CssLexicalTokens.RESIZE},
            {"text-overflow", CssLexicalTokens.TEXTOVERFLOW},
            {"break-after", CssLexicalTokens.BREAKAFTER},
            {"break-before", CssLexicalTokens.BREAKBEFORE},
            {"break-inside", CssLexicalTokens.BREAKINSIDE},
            {"column-count", CssLexicalTokens.COLUMNCOUNT},
            {"column-fill", CssLexicalTokens.COLUMNFILL},
            {"column-gap", CssLexicalTokens.COLUMNGAP},
            {"column-rule", CssLexicalTokens.COLUMNRULE},
            {"column-rule-color", CssLexicalTokens.COLUMNRULECOLOR},
            {"column-rule-style", CssLexicalTokens.COLUMNRULESTYLE},
            {"column-rule-width", CssLexicalTokens.COLUMNRULEWIDTH},
            {"column-span", CssLexicalTokens.COLUMNSPAN},
            {"column-width", CssLexicalTokens.COLUMNWIDTH},
            {"columns", CssLexicalTokens.COLUMNS},
            {"widows", CssLexicalTokens.WIDOWS},
            {"orphans", CssLexicalTokens.ORPHANS},
            {"page-break-after", CssLexicalTokens.PAGEBREAKAFTER},
            {"page-break-before", CssLexicalTokens.PAGEBREAKBEFORE},
            {"page-break-inside", CssLexicalTokens.PAGEBREAKINSIDE},
            {"marks", CssLexicalTokens.MARKS},
            {"quotes", CssLexicalTokens.QUOTES},
            {"filter", CssLexicalTokens.FILTER},
            {"image-orientation", CssLexicalTokens.IMAGEORIENTATION},
            {"image-rendering", CssLexicalTokens.IMAGERENDERING},
            {"image-resolution", CssLexicalTokens.IMAGERESOLUTION},
            {"object-fit", CssLexicalTokens.OBJECTFIT},
            {"object-position", CssLexicalTokens.OBJECTPOSITION},
            {"mask", CssLexicalTokens.MASK},
            {"mask-type", CssLexicalTokens.MASKTYPE},
            {"mark", CssLexicalTokens.MARK},
            {"mark-after", CssLexicalTokens.MARKAFTER},
            {"mark-before", CssLexicalTokens.MARKBEFORE},
            {"phonemes", CssLexicalTokens.PHONEMES},
            {"rest", CssLexicalTokens.REST},
            {"rest-after", CssLexicalTokens.RESTAFTER},
            {"rest-before", CssLexicalTokens.RESTBEFORE},
            {"voice-balance", CssLexicalTokens.VOICEBALANCE},
            {"voice-duration", CssLexicalTokens.VOICEDURATION},
            {"voice-pitch", CssLexicalTokens.VOICEPITCH},
            {"voice-pitch-range", CssLexicalTokens.VOICEPITCHRANGE},
            {"voice-rate", CssLexicalTokens.VOICERATE},
            {"voice-stress", CssLexicalTokens.VOICESTRESS},
            {"voice-volume", CssLexicalTokens.VOICEVOLUME},
            {"marquee-direction", CssLexicalTokens.MARQUEEDIRECTION},
            {"marquee-play-count", CssLexicalTokens.MARQUEEPLAYCOUNT},
            {"marquee-speed", CssLexicalTokens.MARQUEESPEED},
            {"marquee-style", CssLexicalTokens.MARQUEESTYLE}
        };
    }
}
