using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
namespace HTMLUICompiler.CssRuleGroups
{
    public class CssHelpers
    {
        public enum CssRuleGroups
        {
            COLOR,
            BACKGROUNDANDBORDERS,
            BASICBOX,
            FLEXIBLEBOX,
            TEXT,
            TEXTDECORATION,
            FONTS,
            WRITINGMODES,
            TABLE,
            LISTSANDCOUNTERS,
            ANIMATION,
            TRANSFORM,
            TRANSITION,
            BASICUSERINTERFACE,
            MULTICOLUMN,
            PAGEDMEDIA,
            GENERATEDCONTENT,
            FILTEREFFECTS,
            IMAGEREPLACEDCONTENT,
            MASKING,
            SPEECH,
            MARQUEE
        };

        public enum CssRuleTokens
        {
            COLOR,
            OPACITY,
            BACKGROUND,
            BACKGROUNDATTACHMENT,
            BACKGROUNDCOLOR,
            BACKGROUNDIMAGE,
            BACKGROUNDPOSITION,
            BACKGROUNDREPEAT,
            BACKGROUNDCLIP,
            BACKGROUNDORIGIN,
            BACKGROUNDSIZE,
            BORDER,
            BORDERBOTTOM,
            BORDERBOTTOMCOLOR,
            BORDERBOTTOMLEFTRADIUS,
            BORDERBOTTOMRIGHTRADIUS,
            BORDERBOTTOMSTYLE,
            BORDERBOTTOMWIDTH,
            BORDERCOLOR,
            BORDERIMAGE,
            BORDERIMAGEOUTSET,
            BORDERIMAGEREPEAT,
            BORDERIMAGESLICE,
            BORDERIMAGESOURCE,
            BORDERIMAGEWIDTH,
            BORDERLEFT,
            BORDERLEFTCOLOR,
            BORDERLEFTSTYLE,
            BORDERLEFTWIDTH,
            BORDERRADIUS,
            BORDERRIGHT,
            BORDERRIGHTCOLOR,
            BORDERRIGHTSTYLE,
            BORDERRIGHTWIDTH,
            BORDERSTYLE,
            BORDERTOP,
            BORDERTOPCOLOR,
            BORDERTOPLEFTRADIUS,
            BORDERTOPRIGHTRADIUS,
            BORDERTOPSTYLE,
            BORDERTOPWIDTH,
            BORDERWIDTH,
            BOXDECORATIONBREAK,
            BOXSHADOW,
            BOTTOM,
            CLEAR,
            CLIP,
            FLOATING,
            HEIGHT,
            LEFT,
            OVERFLOW,
            OVERFLOWX,
            OVERFLOWY,
            PADDING,
            PADDINGBOTTOM,
            PADDINGLEFT,
            PADDINGRIGHT,
            PADDINGTOP,
            POSITION,
            RIGHT,
            TOP,
            VISIBILITY,
            WIDTH,
            VERTICALALIGN,
            ZINDEX,
            ALIGNCONTENT,
            ALIGNITEMS,
            ALIGNSELF,
            DISPLAY,
            FLEX,
            FLEXBASIS,
            FLEXDIRECTION,
            FLEXFLOW,
            FLEXGROW,
            FLEXSHRINK,
            FLEXWRAP,
            JUSTIFYCONTENT,
            MARGIN,
            MARGINBOTTOM,
            MARGINLEFT,
            MARGINRIGHT,
            MARGINTOP,
            MAXHEIGHT,
            MAXWIDTH,
            MINHEIGHT,
            MINWIDTH,
            ORDER,
            HANGINGPUNCTUATION,
            HYPHENS,
            LETTERSPACING,
            LINEBREAK,
            LINEHEIGHT,
            OVERFLOWWRAP,
            TABSIZE,
            TEXTALIGN,
            TEXTALIGNLAST,
            TEXTINDENT,
            TEXTJUSTIFY,
            TEXTTRANSFORM,
            WHITESPACE,
            WORDBREAK,
            WORDSPACING,
            WORDWRAP,
            TEXTDECORATION,
            TEXTDECORATIONCOLOR,
            TEXTDECORATIONLINE,
            TEXTDECORATIONSTYLE,
            TEXTSHADOW,
            TEXTUNDERLINEPOSITION,
            FONT,
            FONTFAMILY,
            FONTFEATURESETTING,
            FONTFEATUREVALUES,
            FONTKERNING,
            FONTLANGUAGEOVERRIDE,
            FONTSYNTHESIS,
            FONTVARIANTALTERNATES,
            FONTVARIANTCAPS,
            FONTVARIANTEASTASIAN,
            FONTVARIANTLIGATURES,
            FONTVARIANTNUMERIC,
            FONTVARIANTPOSITION,
            FONTSIZE,
            FONTSTYLE,
            FONTVARIANT,
            FONTWEIGHT,
            FONTFACE,
            FONTSIZEADJUST,
            FONTSTRETCH,
            DIRECTION,
            TEXTORIENTATION,
            TEXTCOMBINEHORIZONTAL,
            UNICODEBIDI,
            WRITINGMODE,
            BORDERCOLLAPSE,
            BORDERSPACING,
            CAPTIONSIDE,
            EMPTYCELLS,
            TABLELAYOUT,
            COUNTERINCREMENT,
            COUNTERRESET,
            LISTSTYLE,
            LISTSTYLEIMAGE,
            LISTSTYLEPOSITION,
            LISTSTYLETYPE,
            KEYFRAMES,
            ANIMATION,
            ANIMATIONDELAY,
            ANIMATIONDIRECTION,
            ANIMATIONDURATION,
            ANIMATIONFILLMODE,
            ANIMATIONITERATIONCOUNT,
            ANIMATIONNAME,
            ANIMATIONTIMINGFUNCTION,
            ANIMATIONPLAYSTATE,
            BACKFACEVISIBILITY,
            PERSPECTIVE,
            PERSPECTIVEORIGIN,
            TRANSFORM,
            TRANSFORMORIGIN,
            TRANSFORMSTYLE,
            TRANSITIONPROPERTY,
            TRANSITION,
            TRANSITIONDURATION,
            TRANSITIONTIMINGFUNCTION,
            TRANSITIONDELAY,
            BOXSIZING,
            CONTENT,
            CURSOR,
            ICON,
            IMEMODE,
            NAVDOWN,
            NAVINDEX,
            NAVLEFT,
            NAVRIGHT,
            NAVUP,
            OUTLINE,
            OUTLINECOLOR,
            OUTLINEOFFSET,
            OUTLINESTYLE,
            OUTLINEWIDTH,
            RESIZE,
            TEXTOVERFLOW,
            BREAKAFTER,
            BREAKBEFORE,
            BREAKINSIDE,
            COLUMNCOUNT,
            COLUMNFILL,
            COLUMNGAP,
            COLUMNRULE,
            COLUMNRULECOLOR,
            COLUMNRULESTYLE,
            COLUMNRULEWIDTH,
            COLUMNSPAN,
            COLUMNWIDTH,
            COLUMNS,
            WIDOWS,
            ORPHANS,
            PAGEBREAKAFTER,
            PAGEBREAKBEFORE,
            PAGEBREAKINSIDE,
            MARKS,
            QUOTES,
            FILTER,
            IMAGEORIENTATION,
            IMAGERENDERING,
            IMAGERESOLUTION,
            OBJECTFIT,
            OBJECTPOSITION,
            MASK,
            MASKTYPE,
            MARK,
            MARKAFTER,
            MARKBEFORE,
            PHONEMES,
            REST,
            RESTAFTER,
            RESTBEFORE,
            VOICEBALANCE,
            VOICEDURATION,
            VOICEPITCH,
            VOICEPITCHRANGE,
            VOICERATE,
            VOICESTRESS,
            VOICEVOLUME,
            MARQUEEDIRECTION,
            MARQUEEPLAYCOUNT,
            MARQUEESPEED,
            MARQUEESTYLE
        };

        public class CssCategory
        {
            public CssCategory(CssRuleTokens cssToken, CssRuleGroups cssGroup)
            {
                m_cssToken = cssToken;
                m_cssGroup = cssGroup;
            }
            public CssRuleTokens m_cssToken;
            public CssRuleGroups m_cssGroup;
        }

        public static Dictionary<string, CssCategory> StringToCssCategory = new Dictionary<string, CssCategory>()
        {
            {"color", new CssCategory(CssRuleTokens.COLOR, CssRuleGroups.COLOR) },
            {"opacity", new CssCategory(CssRuleTokens.OPACITY,)},
            {"background", new CssCategory(CssRuleTokens.BACKGROUND,)},
            {"background-attachment", new CssCategory(CssRuleTokens.BACKGROUNDATTACHMENT,)},
            {"background-color", new CssCategory(CssRuleTokens.BACKGROUNDCOLOR,)},
            {"background-image", new CssCategory(CssRuleTokens.BACKGROUNDIMAGE,)},
            {"background-position", new CssCategory(CssRuleTokens.BACKGROUNDPOSITION,)},
            {"background-repeat", new CssCategory(CssRuleTokens.BACKGROUNDREPEAT,)},
            {"background-clip", new CssCategory(CssRuleTokens.BACKGROUNDCLIP,)},
            {"background-origin", new CssCategory(CssRuleTokens.BACKGROUNDORIGIN,)},
            {"background-size", new CssCategory(CssRuleTokens.BACKGROUNDSIZE,)},
            {"border", new CssCategory(CssRuleTokens.BORDER,)},
            {"border-bottom", new CssCategory(CssRuleTokens.BORDERBOTTOM,)},
            {"border-bottom-color", new CssCategory(CssRuleTokens.BORDERBOTTOMCOLOR,)},
            {"border-bottom-left-radius", new CssCategory(CssRuleTokens.BORDERBOTTOMLEFTRADIUS,)},
            {"border-bottom-right-radius", new CssCategory(CssRuleTokens.BORDERBOTTOMRIGHTRADIUS,)},
            {"border-bottom-style", new CssCategory(CssRuleTokens.BORDERBOTTOMSTYLE,)},
            {"border-bottom-width", new CssCategory(CssRuleTokens.BORDERBOTTOMWIDTH,)},
            {"border-color", new CssCategory(CssRuleTokens.BORDERCOLOR,)},
            {"border-image", new CssCategory(CssRuleTokens.BORDERIMAGE,)},
            {"border-image-outset", new CssCategory(CssRuleTokens.BORDERIMAGEOUTSET,)},
            {"border-image-repeat", new CssCategory(CssRuleTokens.BORDERIMAGEREPEAT,)},
            {"border-image-slice", new CssCategory(CssRuleTokens.BORDERIMAGESLICE,)},
            {"border-image-source", new CssCategory(CssRuleTokens.BORDERIMAGESOURCE,)},
            {"border-image-width", new CssCategory(CssRuleTokens.BORDERIMAGEWIDTH,)},
            {"border-left", new CssCategory(CssRuleTokens.BORDERLEFT,)},
            {"border-left-color", new CssCategory(CssRuleTokens.BORDERLEFTCOLOR,)},
            {"border-left-style", new CssCategory(CssRuleTokens.BORDERLEFTSTYLE,)},
            {"border-left-width", new CssCategory(CssRuleTokens.BORDERLEFTWIDTH,)},
            {"border-radius", new CssCategory(CssRuleTokens.BORDERRADIUS,)},
            {"border-right", new CssCategory(CssRuleTokens.BORDERRIGHT,)},
            {"border-right-color", new CssCategory(CssRuleTokens.BORDERRIGHTCOLOR,)},
            {"border-right-style", new CssCategory(CssRuleTokens.BORDERRIGHTSTYLE,)},
            {"border-right-width", new CssCategory(CssRuleTokens.BORDERRIGHTWIDTH,)},
            {"border-style", new CssCategory(CssRuleTokens.BORDERSTYLE,)},
            {"border-top", new CssCategory(CssRuleTokens.BORDERTOP,)},
            {"border-top-color", new CssCategory(CssRuleTokens.BORDERTOPCOLOR,)},
            {"border-top-left-radius", new CssCategory(CssRuleTokens.BORDERTOPLEFTRADIUS,)},
            {"border-top-right-radius", new CssCategory(CssRuleTokens.BORDERTOPRIGHTRADIUS,)},
            {"border-top-style", new CssCategory(CssRuleTokens.BORDERTOPSTYLE,)},
            {"border-top-width", new CssCategory(CssRuleTokens.BORDERTOPWIDTH,)},
            {"border-width", new CssCategory(CssRuleTokens.BORDERWIDTH,)},
            {"box-decoration-break", new CssCategory(CssRuleTokens.BOXDECORATIONBREAK,)},
            {"box-shadow", new CssCategory(CssRuleTokens.BOXSHADOW,)},
            {"bottom", new CssCategory(CssRuleTokens.BOTTOM,)},
            {"clear", new CssCategory(CssRuleTokens.CLEAR,)},
            {"clip", new CssCategory(CssRuleTokens.CLIP,)},
            {"display", new CssCategory(CssRuleTokens.DISPLAY,)},
            {"float", new CssCategory(CssRuleTokens.FLOATING,)},
            {"height", new CssCategory(CssRuleTokens.HEIGHT,)},
            {"left", new CssCategory(CssRuleTokens.LEFT,)},
            {"overflow", new CssCategory(CssRuleTokens.OVERFLOW,)},
            {"overflow-x", new CssCategory(CssRuleTokens.OVERFLOWX,)},
            {"overflow-y", new CssCategory(CssRuleTokens.OVERFLOWY,)},
            {"padding", new CssCategory(CssRuleTokens.PADDING,)},
            {"padding-bottom", new CssCategory(CssRuleTokens.PADDINGBOTTOM,)},
            {"padding-left", new CssCategory(CssRuleTokens.PADDINGLEFT,)},
            {"padding-right", new CssCategory(CssRuleTokens.PADDINGRIGHT,)},
            {"padding-top", new CssCategory(CssRuleTokens.PADDINGTOP,)},
            {"position", new CssCategory(CssRuleTokens.POSITION,)},
            {"right", new CssCategory(CssRuleTokens.RIGHT,)},
            {"top", new CssCategory(CssRuleTokens.TOP,)},
            {"visibility", new CssCategory(CssRuleTokens.VISIBILITY,)},
            {"width", new CssCategory(CssRuleTokens.WIDTH,)},
            {"vertical-align", new CssCategory(CssRuleTokens.VERTICALALIGN,)},
            {"z-index", new CssCategory(CssRuleTokens.ZINDEX,)},
            {"align-content", new CssCategory(CssRuleTokens.ALIGNCONTENT,)},
            {"align-items", new CssCategory(CssRuleTokens.ALIGNITEMS,)},
            {"align-self", new CssCategory(CssRuleTokens.ALIGNSELF,)},
            {"flex", new CssCategory(CssRuleTokens.FLEX,)},
            {"flex-basis", new CssCategory(CssRuleTokens.FLEXBASIS,)},
            {"flex-direction", new CssCategory(CssRuleTokens.FLEXDIRECTION,)},
            {"flex-flow", new CssCategory(CssRuleTokens.FLEXFLOW,)},
            {"flex-grow", new CssCategory(CssRuleTokens.FLEXGROW,)},
            {"flex-shrink", new CssCategory(CssRuleTokens.FLEXSHRINK,)},
            {"flex-wrap", new CssCategory(CssRuleTokens.FLEXWRAP,)},
            {"justify-content", new CssCategory(CssRuleTokens.JUSTIFYCONTENT,)},
            {"margin", new CssCategory(CssRuleTokens.MARGIN,)},
            {"margin-bottom", new CssCategory(CssRuleTokens.MARGINBOTTOM,)},
            {"margin-left", new CssCategory(CssRuleTokens.MARGINLEFT,)},
            {"margin-right", new CssCategory(CssRuleTokens.MARGINRIGHT,)},
            {"margin-top", new CssCategory(CssRuleTokens.MARGINTOP,)},
            {"max-height", new CssCategory(CssRuleTokens.MAXHEIGHT,)},
            {"max-width", new CssCategory(CssRuleTokens.MAXWIDTH,)},
            {"min-height", new CssCategory(CssRuleTokens.MINHEIGHT,)},
            {"min-width", new CssCategory(CssRuleTokens.MINWIDTH,)},
            {"order", new CssCategory(CssRuleTokens.ORDER,)},
            {"hanging-punctuation", new CssCategory(CssRuleTokens.HANGINGPUNCTUATION,)},
            {"hyphens", new CssCategory(CssRuleTokens.HYPHENS,)},
            {"letter-spacing", new CssCategory(CssRuleTokens.LETTERSPACING,)},
            {"line-break", new CssCategory(CssRuleTokens.LINEBREAK,)},
            {"line-height", new CssCategory(CssRuleTokens.LINEHEIGHT,)},
            {"overflow-wrap", new CssCategory(CssRuleTokens.OVERFLOWWRAP,)},
            {"tab-size", new CssCategory(CssRuleTokens.TABSIZE,)},
            {"text-align", new CssCategory(CssRuleTokens.TEXTALIGN,)},
            {"text-align-last", new CssCategory(CssRuleTokens.TEXTALIGNLAST,)},
            {"text-indent", new CssCategory(CssRuleTokens.TEXTINDENT,)},
            {"text-justify", new CssCategory(CssRuleTokens.TEXTJUSTIFY,)},
            {"text-transform", new CssCategory(CssRuleTokens.TEXTTRANSFORM,)},
            {"white-space", new CssCategory(CssRuleTokens.WHITESPACE,)},
            {"word-break", new CssCategory(CssRuleTokens.WORDBREAK,)},
            {"word-spacing", new CssCategory(CssRuleTokens.WORDSPACING,)},
            {"word-wrap", new CssCategory(CssRuleTokens.WORDWRAP,)},
            {"text-decoration", new CssCategory(CssRuleTokens.TEXTDECORATION,)},
            {"text-decoration-color", new CssCategory(CssRuleTokens.TEXTDECORATIONCOLOR,)},
            {"text-decoration-line", new CssCategory(CssRuleTokens.TEXTDECORATIONLINE,)},
            {"text-decoration-style", new CssCategory(CssRuleTokens.TEXTDECORATIONSTYLE,)},
            {"text-shadow", new CssCategory(CssRuleTokens.TEXTSHADOW,)},
            {"text-underline-position", new CssCategory(CssRuleTokens.TEXTUNDERLINEPOSITION,)},
            {"font", new CssCategory(CssRuleTokens.FONT,)},
            {"font-family", new CssCategory(CssRuleTokens.FONTFAMILY,)},
            {"font-feature-setting", new CssCategory(CssRuleTokens.FONTFEATURESETTING,)},
            {"@font-feature-values", new CssCategory(CssRuleTokens.FONTFEATUREVALUES,)},
            {"font-kerning", new CssCategory(CssRuleTokens.FONTKERNING,)},
            {"font-language-override", new CssCategory(CssRuleTokens.FONTLANGUAGEOVERRIDE,)},
            {"font-synthesis", new CssCategory(CssRuleTokens.FONTSYNTHESIS,)},
            {"font-variant-alternates", new CssCategory(CssRuleTokens.FONTVARIANTALTERNATES,)},
            {"font-variant-caps", new CssCategory(CssRuleTokens.FONTVARIANTCAPS,)},
            {"font-variant-east-asian", new CssCategory(CssRuleTokens.FONTVARIANTEASTASIAN,)},
            {"font-variant-ligatures", new CssCategory(CssRuleTokens.FONTVARIANTLIGATURES,)},
            {"font-variant-numeric", new CssCategory(CssRuleTokens.FONTVARIANTNUMERIC,)},
            {"font-variant-position", new CssCategory(CssRuleTokens.FONTVARIANTPOSITION,)},
            {"font-size", new CssCategory(CssRuleTokens.FONTSIZE,)},
            {"font-style", new CssCategory(CssRuleTokens.FONTSTYLE,)},
            {"font-variant", new CssCategory(CssRuleTokens.FONTVARIANT,)},
            {"font-weight", new CssCategory(CssRuleTokens.FONTWEIGHT,)},
            {"@font-face", new CssCategory(CssRuleTokens.FONTFACE,)},
            {"font-size-adjust", new CssCategory(CssRuleTokens.FONTSIZEADJUST,)},
            {"font-stretch", new CssCategory(CssRuleTokens.FONTSTRETCH,)},
            {"direction", new CssCategory(CssRuleTokens.DIRECTION,)},
            {"text-orientation", new CssCategory(CssRuleTokens.TEXTORIENTATION,)},
            {"text-combine-horizontal", new CssCategory(CssRuleTokens.TEXTCOMBINEHORIZONTAL,)},
            {"unicode-bidi", new CssCategory(CssRuleTokens.UNICODEBIDI,)},
            {"writing-mode", new CssCategory(CssRuleTokens.WRITINGMODE,)},
            {"border-collapse", new CssCategory(CssRuleTokens.BORDERCOLLAPSE,)},
            {"border-spacing", new CssCategory(CssRuleTokens.BORDERSPACING,)},
            {"caption-side", new CssCategory(CssRuleTokens.CAPTIONSIDE,)},
            {"empty-cells", new CssCategory(CssRuleTokens.EMPTYCELLS,)},
            {"table-layout", new CssCategory(CssRuleTokens.TABLELAYOUT,)},
            {"counter-increment", new CssCategory(CssRuleTokens.COUNTERINCREMENT,)},
            {"counter-reset", new CssCategory(CssRuleTokens.COUNTERRESET,)},
            {"list-style", new CssCategory(CssRuleTokens.LISTSTYLE,)},
            {"list-style-image", new CssCategory(CssRuleTokens.LISTSTYLEIMAGE,)},
            {"list-style-position", new CssCategory(CssRuleTokens.LISTSTYLEPOSITION,)},
            {"list-style-type", new CssCategory(CssRuleTokens.LISTSTYLETYPE,)},
            {"@keyframes", new CssCategory(CssRuleTokens.KEYFRAMES,)},
            {"animation", new CssCategory(CssRuleTokens.ANIMATION,)},
            {"animation-delay", new CssCategory(CssRuleTokens.ANIMATIONDELAY,)},
            {"animation-direction", new CssCategory(CssRuleTokens.ANIMATIONDIRECTION,)},
            {"animation-duration", new CssCategory(CssRuleTokens.ANIMATIONDURATION,)},
            {"animation-fill-mode", new CssCategory(CssRuleTokens.ANIMATIONFILLMODE,)},
            {"animation-iteration-count", new CssCategory(CssRuleTokens.ANIMATIONITERATIONCOUNT,)},
            {"animation-name", new CssCategory(CssRuleTokens.ANIMATIONNAME,)},
            {"animation-timing-function", new CssCategory(CssRuleTokens.ANIMATIONTIMINGFUNCTION,)},
            {"animation-play-state", new CssCategory(CssRuleTokens.ANIMATIONPLAYSTATE,)},
            {"backface-visibility", new CssCategory(CssRuleTokens.BACKFACEVISIBILITY,)},
            {"perspective", new CssCategory(CssRuleTokens.PERSPECTIVE,)},
            {"perspective-origin", new CssCategory(CssRuleTokens.PERSPECTIVEORIGIN,)},
            {"transform", new CssCategory(CssRuleTokens.TRANSFORM,)},
            {"transform-origin", new CssCategory(CssRuleTokens.TRANSFORMORIGIN,)},
            {"transform-style", new CssCategory(CssRuleTokens.TRANSFORMSTYLE,)},
            {"transition", new CssCategory(CssRuleTokens.TRANSITION,)},
            {"transition-property", new CssCategory(CssRuleTokens.TRANSITIONPROPERTY,)},
            {"transition-duration", new CssCategory(CssRuleTokens.TRANSITIONDURATION,)},
            {"transition-timing-function", new CssCategory(CssRuleTokens.TRANSITIONTIMINGFUNCTION,)},
            {"transition-delay", new CssCategory(CssRuleTokens.TRANSITIONDELAY,)},
            {"box-sizing", new CssCategory(CssRuleTokens.BOXSIZING,)},
            {"content", new CssCategory(CssRuleTokens.CONTENT,)},
            {"cursor", new CssCategory(CssRuleTokens.CURSOR,)},
            {"icon", new CssCategory(CssRuleTokens.ICON,)},
            {"ime-mode", new CssCategory(CssRuleTokens.IMEMODE,)},
            {"nav-down", new CssCategory(CssRuleTokens.NAVDOWN,)},
            {"nav-index", new CssCategory(CssRuleTokens.NAVINDEX,)},
            {"nav-left", new CssCategory(CssRuleTokens.NAVLEFT,)},
            {"nav-right", new CssCategory(CssRuleTokens.NAVRIGHT,)},
            {"nav-up", new CssCategory(CssRuleTokens.NAVUP,)},
            {"outline", new CssCategory(CssRuleTokens.OUTLINE,)},
            {"outline-color", new CssCategory(CssRuleTokens.OUTLINECOLOR,)},
            {"outline-offset", new CssCategory(CssRuleTokens.OUTLINEOFFSET,)},
            {"outline-style", new CssCategory(CssRuleTokens.OUTLINESTYLE,)},
            {"outline-width", new CssCategory(CssRuleTokens.OUTLINEWIDTH,)},
            {"resize", new CssCategory(CssRuleTokens.RESIZE,)},
            {"text-overflow", new CssCategory(CssRuleTokens.TEXTOVERFLOW,)},
            {"break-after", new CssCategory(CssRuleTokens.BREAKAFTER,)},
            {"break-before", new CssCategory(CssRuleTokens.BREAKBEFORE,)},
            {"break-inside", new CssCategory(CssRuleTokens.BREAKINSIDE,)},
            {"column-count", new CssCategory(CssRuleTokens.COLUMNCOUNT,)},
            {"column-fill", new CssCategory(CssRuleTokens.COLUMNFILL,)},
            {"column-gap", new CssCategory(CssRuleTokens.COLUMNGAP,)},
            {"column-rule", new CssCategory(CssRuleTokens.COLUMNRULE,)},
            {"column-rule-color", new CssCategory(CssRuleTokens.COLUMNRULECOLOR,)},
            {"column-rule-style", new CssCategory(CssRuleTokens.COLUMNRULESTYLE,)},
            {"column-rule-width", new CssCategory(CssRuleTokens.COLUMNRULEWIDTH,)},
            {"column-span", new CssCategory(CssRuleTokens.COLUMNSPAN,)},
            {"column-width", new CssCategory(CssRuleTokens.COLUMNWIDTH,)},
            {"columns", new CssCategory(CssRuleTokens.COLUMNS,)},
            {"widows", new CssCategory(CssRuleTokens.WIDOWS,)},
            {"orphans", new CssCategory(CssRuleTokens.ORPHANS,)},
            {"page-break-after", new CssCategory(CssRuleTokens.PAGEBREAKAFTER,)},
            {"page-break-before", new CssCategory(CssRuleTokens.PAGEBREAKBEFORE,)},
            {"page-break-inside", new CssCategory(CssRuleTokens.PAGEBREAKINSIDE,)},
            {"marks", new CssCategory(CssRuleTokens.MARKS,)},
            {"quotes", new CssCategory(CssRuleTokens.QUOTES,)},
            {"filter", new CssCategory(CssRuleTokens.FILTER,)},
            {"image-orientation", new CssCategory(CssRuleTokens.IMAGEORIENTATION,)},
            {"image-rendering", new CssCategory(CssRuleTokens.IMAGERENDERING,)},
            {"image-resolution", new CssCategory(CssRuleTokens.IMAGERESOLUTION,)},
            {"object-fit", new CssCategory(CssRuleTokens.OBJECTFIT,)},
            {"object-position", new CssCategory(CssRuleTokens.OBJECTPOSITION,)},
            {"mask", new CssCategory(CssRuleTokens.MASK,)},
            {"mask-type", new CssCategory(CssRuleTokens.MASKTYPE,)},
            {"mark", new CssCategory(CssRuleTokens.MARK,)},
            {"mark-after", new CssCategory(CssRuleTokens.MARKAFTER,)},
            {"mark-before", new CssCategory(CssRuleTokens.MARKBEFORE,)},
            {"phonemes", new CssCategory(CssRuleTokens.PHONEMES,)},
            {"rest", new CssCategory(CssRuleTokens.REST,)},
            {"rest-after", new CssCategory(CssRuleTokens.RESTAFTER,)},
            {"rest-before", new CssCategory(CssRuleTokens.RESTBEFORE,)},
            {"voice-balance", new CssCategory(CssRuleTokens.VOICEBALANCE,)},
            {"voice-duration", new CssCategory(CssRuleTokens.VOICEDURATION,)},
            {"voice-pitch", new CssCategory(CssRuleTokens.VOICEPITCH,)},
            {"voice-pitch-range", new CssCategory(CssRuleTokens.VOICEPITCHRANGE,)},
            {"voice-rate", new CssCategory(CssRuleTokens.VOICERATE,)},
            {"voice-stress", new CssCategory(CssRuleTokens.VOICESTRESS,)},
            {"voice-volume", new CssCategory(CssRuleTokens.VOICEVOLUME,)},
            {"marquee-direction", new CssCategory(CssRuleTokens.MARQUEEDIRECTION,)},
            {"marquee-play-count", new CssCategory(CssRuleTokens.MARQUEEPLAYCOUNT,)},
            {"marquee-speed", new CssCategory(CssRuleTokens.MARQUEESPEED,)},
            {"marquee-style", new CssCategory(CssRuleTokens.MARQUEESTYLE,)}
        };

        public static Dictionary<string, CssRuleGroups> StringToCssRule = new Dictionary<string, CssRuleGroups>()
        {
            {"color", CssRuleGroups.COLOR},
            {"opacity", CssRuleGroups.COLOR},
            {"background", CssRuleGroups.BACKGROUNDANDBORDERS},
            {"background-attachment", CssRuleGroups.BACKGROUNDANDBORDERS},
            {"background-color", CssRuleGroups.BACKGROUNDANDBORDERS},
            {"background-image", CssRuleGroups.BACKGROUNDANDBORDERS},
            {"background-position", CssRuleGroups.BACKGROUNDANDBORDERS},
            {"background-repeat", CssRuleGroups.BACKGROUNDANDBORDERS},
            {"background-clip", CssRuleGroups.BACKGROUNDANDBORDERS},
            {"background-origin", CssRuleGroups.BACKGROUNDANDBORDERS},
            {"background-size", CssRuleGroups.BACKGROUNDANDBORDERS},
            {"border", CssRuleGroups.BACKGROUNDANDBORDERS},
            {"border-bottom", CssRuleGroups.BACKGROUNDANDBORDERS},
            {"border-bottom-color", CssRuleGroups.BACKGROUNDANDBORDERS},
            {"border-bottom-left-radius", CssRuleGroups.BACKGROUNDANDBORDERS},
            {"border-bottom-right-radius", CssRuleGroups.BACKGROUNDANDBORDERS},
            {"border-bottom-style", CssRuleGroups.BACKGROUNDANDBORDERS},
            {"border-bottom-width", CssRuleGroups.BACKGROUNDANDBORDERS},
            {"border-color", CssRuleGroups.BACKGROUNDANDBORDERS},
            {"border-image", CssRuleGroups.BACKGROUNDANDBORDERS},
            {"border-image-outset", CssRuleGroups.BACKGROUNDANDBORDERS},
            {"border-image-repeat", CssRuleGroups.BACKGROUNDANDBORDERS},
            {"border-image-slice", CssRuleGroups.BACKGROUNDANDBORDERS},
            {"border-image-source", CssRuleGroups.BACKGROUNDANDBORDERS},
            {"border-image-width", CssRuleGroups.BACKGROUNDANDBORDERS},
            {"border-left", CssRuleGroups.BACKGROUNDANDBORDERS},
            {"border-left-color", CssRuleGroups.BACKGROUNDANDBORDERS},
            {"border-left-style", CssRuleGroups.BACKGROUNDANDBORDERS},
            {"border-left-width", CssRuleGroups.BACKGROUNDANDBORDERS},
            {"border-radius", CssRuleGroups.BACKGROUNDANDBORDERS},
            {"border-right", CssRuleGroups.BACKGROUNDANDBORDERS},
            {"border-right-color", CssRuleGroups.BACKGROUNDANDBORDERS},
            {"border-right-style", CssRuleGroups.BACKGROUNDANDBORDERS},
            {"border-right-width", CssRuleGroups.BACKGROUNDANDBORDERS},
            {"border-style", CssRuleGroups.BACKGROUNDANDBORDERS},
            {"border-top", CssRuleGroups.BACKGROUNDANDBORDERS},
            {"border-top-color", CssRuleGroups.BACKGROUNDANDBORDERS},
            {"border-top-left-radius", CssRuleGroups.BACKGROUNDANDBORDERS},
            {"border-top-right-radius", CssRuleGroups.BACKGROUNDANDBORDERS},
            {"border-top-style", CssRuleGroups.BACKGROUNDANDBORDERS},
            {"border-top-width", CssRuleGroups.BACKGROUNDANDBORDERS},
            {"border-width", CssRuleGroups.BACKGROUNDANDBORDERS},
            {"box-decoration-break", CssRuleGroups.BACKGROUNDANDBORDERS},
            {"box-shadow", CssRuleGroups.BACKGROUNDANDBORDERS},
            {"bottom", CssRuleGroups.BASICBOX},
            {"clear", CssRuleGroups.BASICBOX},
            {"clip", CssRuleGroups.BASICBOX},
            {"display", CssRuleGroups.BASICBOX},
            {"float", CssRuleGroups.BASICBOX},
            {"height", CssRuleGroups.BASICBOX},
            {"left", CssRuleGroups.BASICBOX},
            {"overflow", CssRuleGroups.BASICBOX},
            {"overflow-x", CssRuleGroups.BASICBOX},
            {"overflow-y", CssRuleGroups.BASICBOX},
            {"padding", CssRuleGroups.BASICBOX},
            {"padding-bottom", CssRuleGroups.BASICBOX},
            {"padding-left", CssRuleGroups.BASICBOX},
            {"padding-right", CssRuleGroups.BASICBOX},
            {"padding-top", CssRuleGroups.BASICBOX},
            {"position", CssRuleGroups.BASICBOX},
            {"right", CssRuleGroups.BASICBOX},
            {"top", CssRuleGroups.BASICBOX},
            {"visibility", CssRuleGroups.BASICBOX},
            {"width", CssRuleGroups.BASICBOX},
            {"vertical-align", CssRuleGroups.BASICBOX},
            {"z-index", CssRuleGroups.BASICBOX},
            {"align-content", CssRuleGroups.FLEXIBLEBOX},
            {"align-items", CssRuleGroups.FLEXIBLEBOX},
            {"align-self", CssRuleGroups.FLEXIBLEBOX},
            {"flex", CssRuleGroups.FLEXIBLEBOX},
            {"flex-basis", CssRuleGroups.FLEXIBLEBOX},
            {"flex-direction", CssRuleGroups.FLEXIBLEBOX},
            {"flex-flow", CssRuleGroups.FLEXIBLEBOX},
            {"flex-grow", CssRuleGroups.FLEXIBLEBOX},
            {"flex-shrink", CssRuleGroups.FLEXIBLEBOX},
            {"flex-wrap", CssRuleGroups.FLEXIBLEBOX},
            {"justify-content", CssRuleGroups.FLEXIBLEBOX},
            {"margin", CssRuleGroups.FLEXIBLEBOX},
            {"margin-bottom", CssRuleGroups.FLEXIBLEBOX},
            {"margin-left", CssRuleGroups.FLEXIBLEBOX},
            {"margin-right", CssRuleGroups.FLEXIBLEBOX},
            {"margin-top", CssRuleGroups.FLEXIBLEBOX},
            {"max-height", CssRuleGroups.FLEXIBLEBOX},
            {"max-width", CssRuleGroups.FLEXIBLEBOX},
            {"min-height", CssRuleGroups.FLEXIBLEBOX},
            {"min-width", CssRuleGroups.FLEXIBLEBOX},
            {"order", CssRuleGroups.FLEXIBLEBOX},
            {"hanging-punctuation", CssRuleGroups.TEXT},
            {"hyphens", CssRuleGroups.TEXT},
            {"letter-spacing", CssRuleGroups.TEXT},
            {"line-break", CssRuleGroups.TEXT},
            {"line-height", CssRuleGroups.TEXT},
            {"overflow-wrap", CssRuleGroups.TEXT},
            {"tab-size", CssRuleGroups.TEXT},
            {"text-align", CssRuleGroups.TEXT},
            {"text-align-last", CssRuleGroups.TEXT},
            {"text-indent", CssRuleGroups.TEXT},
            {"text-justify", CssRuleGroups.TEXT},
            {"text-transform", CssRuleGroups.TEXT},
            {"white-space", CssRuleGroups.TEXT},
            {"word-break", CssRuleGroups.TEXT},
            {"word-spacing", CssRuleGroups.TEXT},
            {"word-wrap", CssRuleGroups.TEXT},
            {"text-decoration", CssRuleGroups.TEXTDECORATION},
            {"text-decoration-color", CssRuleGroups.TEXTDECORATION},
            {"text-decoration-line", CssRuleGroups.TEXTDECORATION},
            {"text-decoration-style", CssRuleGroups.TEXTDECORATION},
            {"text-shadow", CssRuleGroups.TEXTDECORATION},
            {"text-underline-position", CssRuleGroups.TEXTDECORATION},
            {"font", CssRuleGroups.FONTS},
            {"font-family", CssRuleGroups.FONTS},
            {"font-feature-setting", CssRuleGroups.FONTS},
            {"@font-feature-values", CssRuleGroups.FONTS},
            {"font-kerning", CssRuleGroups.FONTS},
            {"font-language-override", CssRuleGroups.FONTS},
            {"font-synthesis", CssRuleGroups.FONTS},
            {"font-variant-alternates", CssRuleGroups.FONTS},
            {"font-variant-caps", CssRuleGroups.FONTS},
            {"font-variant-east-asian", CssRuleGroups.FONTS},
            {"font-variant-ligatures", CssRuleGroups.FONTS},
            {"font-variant-numeric", CssRuleGroups.FONTS},
            {"font-variant-position", CssRuleGroups.FONTS},
            {"font-size", CssRuleGroups.FONTS},
            {"font-style", CssRuleGroups.FONTS},
            {"font-variant", CssRuleGroups.FONTS},
            {"font-weight", CssRuleGroups.FONTS},
            {"@font-face", CssRuleGroups.FONTS},
            {"font-size-adjust", CssRuleGroups.FONTS},
            {"font-stretch", CssRuleGroups.FONTS},
            {"direction", CssRuleGroups.WRITINGMODES},
            {"text-orientation", CssRuleGroups.WRITINGMODES},
            {"text-combine-horizontal", CssRuleGroups.WRITINGMODES},
            {"unicode-bidi", CssRuleGroups.WRITINGMODES},
            {"writing-mode", CssRuleGroups.WRITINGMODES},
            {"border-collapse", CssRuleGroups.TABLE},
            {"border-spacing", CssRuleGroups.TABLE},
            {"caption-side", CssRuleGroups.TABLE},
            {"empty-cells", CssRuleGroups.TABLE},
            {"table-layout", CssRuleGroups.TABLE},
            {"counter-increment", CssRuleGroups.LISTSANDCOUNTERS},
            {"counter-reset", CssRuleGroups.LISTSANDCOUNTERS},
            {"list-style", CssRuleGroups.LISTSANDCOUNTERS},
            {"list-style-image", CssRuleGroups.LISTSANDCOUNTERS},
            {"list-style-position", CssRuleGroups.LISTSANDCOUNTERS},
            {"list-style-type", CssRuleGroups.LISTSANDCOUNTERS},
            {"@keyframes", CssRuleGroups.ANIMATION},
            {"animation", CssRuleGroups.ANIMATION},
            {"animation-delay", CssRuleGroups.ANIMATION},
            {"animation-direction", CssRuleGroups.ANIMATION},
            {"animation-duration", CssRuleGroups.ANIMATION},
            {"animation-fill-mode", CssRuleGroups.ANIMATION},
            {"animation-iteration-count", CssRuleGroups.ANIMATION},
            {"animation-name", CssRuleGroups.ANIMATION},
            {"animation-timing-function", CssRuleGroups.ANIMATION},
            {"animation-play-state", CssRuleGroups.ANIMATION},
            {"backface-visibility", CssRuleGroups.TRANSFORM},
            {"perspective", CssRuleGroups.TRANSFORM},
            {"perspective-origin", CssRuleGroups.TRANSFORM},
            {"transform", CssRuleGroups.TRANSFORM},
            {"transform-origin", CssRuleGroups.TRANSFORM},
            {"transform-style", CssRuleGroups.TRANSFORM},
            {"transition", CssRuleGroups.TRANSITION},
            {"transition-property", CssRuleGroups.TRANSITION},
            {"transition-duration", CssRuleGroups.TRANSITION},
            {"transition-timing-function", CssRuleGroups.TRANSITION},
            {"transition-delay", CssRuleGroups.TRANSITION},
            {"box-sizing", CssRuleGroups.BASICUSERINTERFACE},
            {"content", CssRuleGroups.BASICUSERINTERFACE},
            {"cursor", CssRuleGroups.BASICUSERINTERFACE},
            {"icon", CssRuleGroups.BASICUSERINTERFACE},
            {"ime-mode", CssRuleGroups.BASICUSERINTERFACE},
            {"nav-down", CssRuleGroups.BASICUSERINTERFACE},
            {"nav-index", CssRuleGroups.BASICUSERINTERFACE},
            {"nav-left", CssRuleGroups.BASICUSERINTERFACE},
            {"nav-right", CssRuleGroups.BASICUSERINTERFACE},
            {"nav-up", CssRuleGroups.BASICUSERINTERFACE},
            {"outline", CssRuleGroups.BASICUSERINTERFACE},
            {"outline-color", CssRuleGroups.BASICUSERINTERFACE},
            {"outline-offset", CssRuleGroups.BASICUSERINTERFACE},
            {"outline-style", CssRuleGroups.BASICUSERINTERFACE},
            {"outline-width", CssRuleGroups.BASICUSERINTERFACE},
            {"resize", CssRuleGroups.BASICUSERINTERFACE},
            {"text-overflow", CssRuleGroups.BASICUSERINTERFACE},
            {"break-after", CssRuleGroups.MULTICOLUMN},
            {"break-before", CssRuleGroups.MULTICOLUMN},
            {"break-inside", CssRuleGroups.MULTICOLUMN},
            {"column-count", CssRuleGroups.MULTICOLUMN},
            {"column-fill", CssRuleGroups.MULTICOLUMN},
            {"column-gap", CssRuleGroups.MULTICOLUMN},
            {"column-rule", CssRuleGroups.MULTICOLUMN},
            {"column-rule-color", CssRuleGroups.MULTICOLUMN},
            {"column-rule-style", CssRuleGroups.MULTICOLUMN},
            {"column-rule-width", CssRuleGroups.MULTICOLUMN},
            {"column-span", CssRuleGroups.MULTICOLUMN},
            {"column-width", CssRuleGroups.MULTICOLUMN},
            {"columns", CssRuleGroups.MULTICOLUMN},
            {"widows", CssRuleGroups.MULTICOLUMN},
            {"orphans", CssRuleGroups.PAGEDMEDIA},
            {"page-break-after", CssRuleGroups.PAGEDMEDIA},
            {"page-break-before", CssRuleGroups.PAGEDMEDIA},
            {"page-break-inside", CssRuleGroups.PAGEDMEDIA},
            {"marks", CssRuleGroups.GENERATEDCONTENT},
            {"quotes", CssRuleGroups.GENERATEDCONTENT},
            {"filter", CssRuleGroups.FILTEREFFECTS},
            {"image-orientation", CssRuleGroups.IMAGEREPLACEDCONTENT},
            {"image-rendering", CssRuleGroups.IMAGEREPLACEDCONTENT},
            {"image-resolution", CssRuleGroups.IMAGEREPLACEDCONTENT},
            {"object-fit", CssRuleGroups.IMAGEREPLACEDCONTENT},
            {"object-position", CssRuleGroups.IMAGEREPLACEDCONTENT},
            {"mask", CssRuleGroups.MASKING},
            {"mask-type", CssRuleGroups.MASKING},
            {"mark", CssRuleGroups.SPEECH},
            {"mark-after", CssRuleGroups.SPEECH},
            {"mark-before", CssRuleGroups.SPEECH},
            {"phonemes", CssRuleGroups.SPEECH},
            {"rest", CssRuleGroups.SPEECH},
            {"rest-after", CssRuleGroups.SPEECH},
            {"rest-before", CssRuleGroups.SPEECH},
            {"voice-balance", CssRuleGroups.SPEECH},
            {"voice-duration", CssRuleGroups.SPEECH},
            {"voice-pitch", CssRuleGroups.SPEECH},
            {"voice-pitch-range", CssRuleGroups.SPEECH},
            {"voice-rate", CssRuleGroups.SPEECH},
            {"voice-stress", CssRuleGroups.SPEECH},
            {"voice-volume", CssRuleGroups.SPEECH},
            {"marquee-direction", CssRuleGroups.MARQUEE},
            {"marquee-play-count", CssRuleGroups.MARQUEE},
            {"marquee-speed", CssRuleGroups.MARQUEE},
            {"marquee-style", CssRuleGroups.MARQUEE}
        };
    }
}
